name: Deploy maskinporten-client

on:
  push:
    branches: [ main ]

permissions: write-all

env:
  IMAGE: ghcr.io/navikt/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v2.8.0
        with:
          arguments: test app:buildFatJar --continue --no-daemon --configuration-cache

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker build --pull --tag ${{ env.IMAGE }} --tag ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/navikt/${{ github.repository }} --all-tags

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/app.yml
          VARS: .nais/dev.yml
