name: PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: test app:buildFatJar --continue --no-daemon --configuration-cache
